
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFERENCIA = 16;
  public static final int PYC = 10;
  public static final int DOSPUNTOS = 9;
  public static final int IGUAL = 11;
  public static final int CONJUNTO = 8;
  public static final int PARIZQ = 18;
  public static final int INTERSECCION = 14;
  public static final int PARDER = 19;
  public static final int OPERA = 12;
  public static final int ID = 3;
  public static final int LLAVEIZQ = 4;
  public static final int COMA = 7;
  public static final int LLAVEDER = 5;
  public static final int EOF = 0;
  public static final int UNION = 13;
  public static final int error = 1;
  public static final int NUMERO = 2;
  public static final int COMPLEMENTO = 15;
  public static final int EVALUAR = 17;
  public static final int RANGO = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "ID",
  "LLAVEIZQ",
  "LLAVEDER",
  "RANGO",
  "COMA",
  "CONJUNTO",
  "DOSPUNTOS",
  "PYC",
  "IGUAL",
  "OPERA",
  "UNION",
  "INTERSECCION",
  "COMPLEMENTO",
  "DIFERENCIA",
  "EVALUAR",
  "PARIZQ",
  "PARDER"
  };
}

