
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 16;
  public static final int RAIZ = 11;
  public static final int PYC = 7;
  public static final int CADENA = 6;
  public static final int DECIMAL = 3;
  public static final int PARIZQ = 8;
  public static final int IMPRIMIR = 18;
  public static final int PARDER = 9;
  public static final int UMENOS = 17;
  public static final int MODULO = 14;
  public static final int POR = 12;
  public static final int BOOLEANO = 4;
  public static final int CARACTER = 5;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int error = 1;
  public static final int POTE = 10;
  public static final int ENTERO = 2;
  public static final int MAS = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "DECIMAL",
  "BOOLEANO",
  "CARACTER",
  "CADENA",
  "PYC",
  "PARIZQ",
  "PARDER",
  "POTE",
  "RAIZ",
  "POR",
  "DIV",
  "MODULO",
  "MAS",
  "MENOS",
  "UMENOS",
  "IMPRIMIR"
  };
}

